### ISSUE TITLE
smart loading of sources

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#111] opened 2020-03-31 12:11 UTC
Hi,

would it be possible to set certain properties of sources automatically based on what the data looks like?

Projection modes for example:
- if more than one channel in the data: set to **Sum**
- if min(data) > 20% of max(data): set to **Avg** (likely to be Brightfield images instead of Fluorescence)

Or channels:
if multiple channels:
- preset ch0,ch1,ch2 with RGB color map

As an alternative, we could write some of these settings directly into the xml with non-standard tags.

**Comment by NicoKiaru** [comment] 2020-03-31 13:20
Do I have a repo that reads and build a dataset by using BioFormats. Is the settings can be read with bioformats, then they are applied directly and the saved dataset contains the display information.

If no displaysettings are found within the xml dataset, we could think of something like that yes.

**Comment by martinschorb** [comment] 2020-03-31 13:24
So currently displaysettings contains:

```
<Attributes name="displaysettings">
        <displaysettings>
          <id>0</id>
          <isset>true</isset>
          <color>255 255 255 255</color>
          <min>60.0</min>
          <max>110.0</max>
        </displaysettings>
```

This means I can assign this to the source already when creating the xml, correct? I will play with it...

What is missing is the Projection Modes. I wonder if we should just put them in there with a new tag.

**Comment by martinschorb** [comment] 2020-03-31 13:24
maybe as a new ```projectionmode``` Attribute...

**Comment by martinschorb** [comment] 2020-03-31 13:25
that should cover everything indeed...

**Comment by NicoKiaru** [comment] 2020-03-31 13:39
> This means I can assign this to the source already when creating the xml, correct? I will play with it...

Yep, just note that it is only recognized into the playground currently. I will post in gitter whether people would like to have this supported more generally.

> maybe as a new `projectionmode` Attribute...

I think a tag in `displaysettings` makes sense. After all it's a display setting ...

**Comment by martinschorb** [comment] 2020-03-31 13:44
Agree

**Comment by NicoKiaru** [comment] 2020-03-31 14:27
> Yep, just note that it is only recognized into the playground currently. I will post in gitter whether people would like to have this supported more generally.

https://gitter.im/bigdataviewer/bigdataviewer-core?at=5e8351db419c4a022ec210bc

**Comment by constantinpape** [comment] 2020-04-03 18:47
In the display settings, is the field `id` required?

**Comment by NicoKiaru** [comment] 2020-04-04 17:39
> In the display settings, is the field `id` required?

Yes, I think so, each ViewSetup should identify the display settings in a unique way, and at the moment it's linking ViewSetup display settings by joining `viewSetup.attributes.displaysettings` with `displaysettings.id`
For instance, if you look at at xml file, this `ViewSetup`:
```
<ViewSetup>
        <id>1</id>
        <name>Mandelbrot Set_xfm_0_ResampledLike_Voronoi_256 Pts_[512,512,1]</name>
        <size>512 512 1</size>
        <attributes>
          <channel>1</channel>
          <displaysettings>1</displaysettings>
        </attributes>
      </ViewSetup>
```
Will be linked to this display settings, thanks to its id:
```
<displaysettings>
          <id>1</id>
          <isset>true</isset>
          <color>0 255 0 255</color>
          <min>10.0</min>
          <max>260.0</max>
        </displaysettings>
```

**Comment by martinschorb** [comment] 2020-04-17 10:25
Is there an attribute for the projection modes available in ```displaysettings``` by now?

**Comment by NicoKiaru** [comment] 2020-04-17 10:51
Not yet! Will try to do this afternoon.

**Comment by NicoKiaru** [comment] 2020-04-17 13:40
Ok, done in the fiji update, let me know if some things are broken.

 see commit https://github.com/bigdataviewer/bigdataviewer-playground/commit/7411636a89c31edb5805f0bf34cda81d284f7300

For the record @tischi, I had to make a `Projection.PROJECTION_MODE_XML` attribute, because simply removing the space in "Projection Mode" to make a valid storable xml attribute broke the way the projector is working. I couldn't find why. Not a big deal, but weird.

I'll close this issue. I believe that with this attribute you can set your xml in the way you like it @martinschorb  ?

**Comment by martinschorb** [comment] 2020-04-17 14:07
Hi,
is it also implemented for saving?
I tried to first save some sources to get the proper Values and Tags, but I don' t see it...

```
        <displaysettings>
          <id>2</id>
          <isset>true</isset>
          <color>51 255 51 255</color>
          <min>20.0</min>
          <max>150.0</max>
        </displaysettings>
```
[displaysettings.zip](https://github.com/bigdataviewer/bigdataviewer-playground/files/4493397/displaysettings.zip)

**Comment by martinschorb** [comment] 2020-04-17 14:08
otherwise, what are the correct tags and property definitions to make it work I create an xml myself?

**Comment by NicoKiaru** [comment] 2020-04-17 14:13
Yes it's implemented for saving. Have you tried making a source in average mode and saving it ? It should be like:
```
 <displaysettings>
          <id>1</id>
          <isset>true</isset>
          <color>255 0 51 255</color>
          <min>0.0</min>
          <max>255.0</max>
          <Projection_Mode>Average</Projection_Mode>
        </displaysettings>
```

**Comment by martinschorb** [comment] 2020-04-17 14:19
Hmm,
I don't get the Projection_Mode...
The file I attached above is in fact mixed sources to check if it saves that as well.

Ran the latest Fiji update. There was some confusion with old playground versions.

Seems to be solved now.
Thanks!!

**Comment by martinschorb** [comment] 2020-04-17 14:22
Hmm,

it seems not to take the Average in a mixed setting.
They are all "Sum"

**Comment by martinschorb** [comment] 2020-04-17 14:24
OK, even in the single source export. I get "Sum", although it is clearly "Average" in the viewer.

**Comment by NicoKiaru** [comment] 2020-04-17 16:23
Weird! Do you confirm you have the version 0.1.8 of bigdataviewer-playground?

I tried this and it worked:
```
<Attributes name="displaysettings">
        <displaysettings>
          <id>0</id>
          <isset>true</isset>
          <color>255 0 51 255</color>
          <min>0.0</min>
          <max>255.0</max>
          <Projection_Mode>Average</Projection_Mode>
        </displaysettings>
        <displaysettings>
          <id>2</id>
          <isset>true</isset>
          <color>0 153 153 255</color>
          <min>0.0</min>
          <max>255.0</max>
          <Projection_Mode>SumOccluding</Projection_Mode>
        </displaysettings>
        <displaysettings>
          <id>3</id>
          <isset>true</isset>
          <color>0 255 0 255</color>
          <min>0.0</min>
          <max>255.0</max>
          <Projection_Mode>Average</Projection_Mode>
        </displaysettings>
</Attributes>
```

I need to find a simple way to reproduce the issue

**Comment by martinschorb** [comment] 2020-04-20 12:24
Just tried again.

Fresh fiji update.
![image](https://user-images.githubusercontent.com/35071867/79751081-46481300-8312-11ea-930b-690bce1f9a6e.png)

Using these files:

[m_121.zip](https://github.com/bigdataviewer/bigdataviewer-playground/files/4503429/m_121.zip)

- set color of the fm to green
- set PMode of fm to ```sum```
- set PMode of m_121 to ```Average```

exporting gives:

[pmodes.zip](https://github.com/bigdataviewer/bigdataviewer-playground/files/4503437/pmodes.zip)

with both as ```sum```

```
<Attributes name="displaysettings">
        <displaysettings>
          <id>0</id>
          <isset>true</isset>
          <color>255 255 255 255</color>
          <min>16255.0</min>
          <max>25983.0</max>
          <Projection_Mode>Sum</Projection_Mode>
        </displaysettings>
        <displaysettings>
          <id>1</id>
          <isset>true</isset>
          <color>102 255 102 255</color>
          <min>10.0</min>
          <max>180.0</max>
          <Projection_Mode>Sum</Projection_Mode>
        </displaysettings>
      </Attributes>
```

**Comment by NicoKiaru** [comment] 2020-04-20 15:22
Ok, and just to make sure, if you modify the xml and set the projection mode to `Average` and reopen it, can you get the right projection ?

**Comment by martinschorb** [comment] 2020-04-20 15:28
confirm,
works after manually changing it.

**Comment by NicoKiaru** [comment] 2020-04-20 15:29
:+1:, I'll check the saving

**Comment by martinschorb** [comment] 2020-04-21 07:27
Hi,

now, that I tried creating the ```displaysettings``` myself, I get the following error when loading the sources.

```
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:309)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:163)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:305)
	... 5 more
Caused by: java.lang.NullPointerException
	at sc.fiji.bdvpg.scijava.services.ui.BdvSourceServiceUI.lambda$addEntityFilterNodes$16(BdvSourceServiceUI.java:379)
	at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:907)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at sc.fiji.bdvpg.scijava.services.ui.BdvSourceServiceUI.addEntityFilterNodes(BdvSourceServiceUI.java:379)
	at sc.fiji.bdvpg.scijava.services.ui.BdvSourceServiceUI.lambda$updateSpimDataFilterNodes$12(BdvSourceServiceUI.java:354)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at sc.fiji.bdvpg.scijava.services.ui.BdvSourceServiceUI.updateSpimDataFilterNodes(BdvSourceServiceUI.java:349)
	at sc.fiji.bdvpg.scijava.services.ui.BdvSourceServiceUI.update(BdvSourceServiceUI.java:313)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterService.lambda$register$2(SourceAndConverterService.java:179)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterService.register(SourceAndConverterService.java:177)
	at sc.fiji.bdvpg.spimdata.importer.SpimDataFromXmlImporter.apply(SpimDataFromXmlImporter.java:37)
	at sc.fiji.bdvpg.spimdata.importer.SpimDataFromXmlImporter.get(SpimDataFromXmlImporter.java:29)
	at sc.fiji.bdvpg.scijava.command.spimdata.MultipleSpimDataImporterCommand.run(MultipleSpimDataImporterCommand.java:28)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```
with this file:

```
<SpimData version="0.2">
  <BasePath type="relative">.</BasePath>
  <SequenceDescription>
    <ImageLoader format="bdv.hdf5">
      <hdf5 type="relative">fm_r1.h5</hdf5>
    </ImageLoader>
    <ViewSetups>
      <Attributes name="displaysettings">
        <Displaysettings>
          <id>0</id>
          <Projection_Mode>Sum</Projection_Mode>
          <color>255 0 0 255</color>
        </Displaysettings>
        <Displaysettings>
          <id>1</id>
          <Projection_Mode>Sum</Projection_Mode>
          <color>0 255 0 255</color>
        </Displaysettings>
        <Displaysettings>
          <id>2</id>
          <Projection_Mode>Sum</Projection_Mode>
          <color>0 0 255 255</color>
        </Displaysettings>
      </Attributes>
      <Attributes name="channel">
        <Channel>
          <id>0</id>
        </Channel>
        <Channel>
          <id>1</id>
        </Channel>
        <Channel>
          <id>2</id>
        </Channel>
      </Attributes>
      <ViewSetup>
        <id>0</id>
        <name>fm_r1_R</name>
        <size>936 952 1</size>
        <voxelSize>
          <unit>um</unit>
          <size>0.10054444181020279 0.10054444181020279 0.10054444181020279</size>
        </voxelSize>
        <attributes>
          <displaysettings>0</displaysettings>
          <channel>0</channel>
        </attributes>
      </ViewSetup>
      <ViewSetup>
        <id>1</id>
        <name>fm_r1_G</name>
        <size>936 952 1</size>
        <voxelSize>
          <unit>um</unit>
          <size>0.10054444181020279 0.10054444181020279 0.10054444181020279</size>
        </voxelSize>
        <attributes>
          <displaysettings>1</displaysettings>
          <channel>1</channel>
        </attributes>
      </ViewSetup>
      <ViewSetup>
        <id>2</id>
        <name>fm_r1_B</name>
        <size>936 952 1</size>
        <voxelSize>
          <unit>um</unit>
          <size>0.10054444181020279 0.10054444181020279 0.10054444181020279</size>
        </voxelSize>
        <attributes>
          <displaysettings>2</displaysettings>
          <channel>2</channel>
        </attributes>
      </ViewSetup>
    </ViewSetups>
    <Timepoints type="range">
      <first>0</first>
      <last>0</last>
    </Timepoints>
  </SequenceDescription>
  <ViewRegistrations>
    <ViewRegistration setup="0" timepoint="0">
      <ViewTransform type="affine">
        <affine>1.0 0.0 0.0 360.254 0.0 1.0 0.0 -237.461 0.0 0.0 1.0 0.0</affine>
        <Name>Translation</Name>
      </ViewTransform>
      <ViewTransform type="affine">
        <affine>-0.0971943526895857 -0.02334524150181988 0.0 0.0 -0.025424700810844806 0.09790320872628396 0.0 0.0 0.0 0.0 1.0 0.0</affine>
        <Name>MapScaleMat</Name>
      </ViewTransform>
    </ViewRegistration>
    <ViewRegistration setup="1" timepoint="0">
      <ViewTransform type="affine">
        <affine>1.0 0.0 0.0 360.254 0.0 1.0 0.0 -237.461 0.0 0.0 1.0 0.0</affine>
        <Name>Translation</Name>
      </ViewTransform>
      <ViewTransform type="affine">
        <affine>-0.0971943526895857 -0.02334524150181988 0.0 0.0 -0.025424700810844806 0.09790320872628396 0.0 0.0 0.0 0.0 1.0 0.0</affine>
        <Name>MapScaleMat</Name>
      </ViewTransform>
    </ViewRegistration>
    <ViewRegistration setup="2" timepoint="0">
      <ViewTransform type="affine">
        <affine>1.0 0.0 0.0 360.254 0.0 1.0 0.0 -237.461 0.0 0.0 1.0 0.0</affine>
        <Name>Translation</Name>
      </ViewTransform>
      <ViewTransform type="affine">
        <affine>-0.0971943526895857 -0.02334524150181988 0.0 0.0 -0.025424700810844806 0.09790320872628396 0.0 0.0 0.0 0.0 1.0 0.0</affine>
        <Name>MapScaleMat</Name>
      </ViewTransform>
    </ViewRegistration>
  </ViewRegistrations>
</SpimData>
```

Can you spot what goes wrong??

**Comment by constantinpape** [comment] 2020-04-21 09:20
@martinschorb brought up in https://github.com/constantinpape/pybdv/issues/11 that this is probably caused by the fact that the field name `Displaysettings` is capitalized by `pybdv`, whereas the java consumer expects it to be lower case.

I chose to capitalize it, because this is in line with how the names for other attributes are stored in the original BDV xml spec, e.g. for `channel`:
```
<SequenceDescription>
   <ViewSetups>
      <Attributes name="channel">
        <Channel>
     ....
   <ViewSetup>
     <attributes>
        <channel>1</channel>
```

@NicoKiaru Would it be possible to adapt it so that `displaysettings` fits this pattern as well? 
If it is too much work for you to change this, I could include a special case for `displaysettings`.
That's super easy from my side, but if possble I would like to avoid special cases like this.

**Comment by NicoKiaru** [comment] 2020-04-21 11:03
ok, then `DisplaySettings` ? This would fit with `ViewAttribute, ViewRegistration, etc.`

**Comment by NicoKiaru** [comment] 2020-04-21 11:04
> @NicoKiaru Would it be possible to adapt it so that `displaysettings` fits this pattern as well?
> If it is too much work for you to change this, I could include a special case for `displaysettings`.
> That's super easy from my side, but if possble I would like to avoid special cases like this.

No no, nothing's engraved now, there's no release, only @martinschorb could suffer ( sorry about that ;-)

**Comment by NicoKiaru** [comment] 2020-04-21 11:05
@constantinpape tell me : `Displaysettings` or `DisplaySettings` ? For me it's the same

**Comment by constantinpape** [comment] 2020-04-21 11:08
> @constantinpape tell me : `Displaysettings` or `DisplaySettings` ? For me it's the same

Ok, then please go with `Displaysettings` :)

(Yes `DisplaySettings` would be more consistent with `ViewSetup` etc., however it would introduce more complications: I am supporting to pass arbitrary attribute names now, but they must be lower case and will then be capitalized in the `Attributes` fields to be consistent with `channel` etc in big-data-viewer).

**Comment by NicoKiaru** [comment] 2020-04-21 12:21
RAAAAAAAAAaaaah ! This is super annoying, and I can't even know what's wrong...

Just ranting, please ignore

**Comment by NicoKiaru** [comment] 2020-04-21 15:03
Ok, done and pushed to the update site @martinschorb @constantinpape . If you have old xml files, you need to add manually the capital d in the Displaysettings tag.

The saving of the projection modes should also be fixed.

**Comment by martinschorb** [comment] 2020-04-22 09:47
Still...

```
java.lang.NullPointerException
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at mpicbg.spim.data.XmlHelpers.getDouble(XmlHelpers.java:98)
	at spimdata.util.XmlIoDisplaysettings.fromXml(XmlIoDisplaysettings.java:39)
	at spimdata.util.XmlIoDisplaysettings.fromXml(XmlIoDisplaysettings.java:10)
	at mpicbg.spim.data.generic.base.XmlIoEntityMap.fromXml(XmlIoEntityMap.java:99)
	at mpicbg.spim.data.generic.sequence.XmlIoBasicViewSetups.fromXml(XmlIoBasicViewSetups.java:131)
	at mpicbg.spim.data.generic.sequence.XmlIoAbstractSequenceDescription.fromXml(XmlIoAbstractSequenceDescription.java:96)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.fromXml(XmlIoAbstractSpimData.java:153)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:95)
	at sc.fiji.bdvpg.spimdata.importer.SpimDataFromXmlImporter.apply(SpimDataFromXmlImporter.java:36)
	at sc.fiji.bdvpg.spimdata.importer.SpimDataFromXmlImporter.get(SpimDataFromXmlImporter.java:29)
	at sc.fiji.bdvpg.scijava.command.spimdata.MultipleSpimDataImporterCommand.run(MultipleSpimDataImporterCommand.java:28)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

with these files...

[m_121.zip](https://github.com/bigdataviewer/bigdataviewer-playground/files/4515291/m_121.zip)

what's wrong...?

```
<SpimData version="0.2">
  <BasePath type="relative">.</BasePath>
  <SequenceDescription>
    <ImageLoader format="bdv.hdf5">
      <hdf5 type="relative">m_121.h5</hdf5>
    </ImageLoader>
    <ViewSetups>
      <Attributes name="displaysettings">
        <Displaysettings>
          <id>0</id>
          <color>255 255 255 255</color>
          <Projection_Mode>Average</Projection_Mode>
        </Displaysettings>
      </Attributes>
      <ViewSetup>
        <id>0</id>
        <name>m_121</name>
        <size>2024 2024 1</size>
        <voxelSize>
          <unit>um</unit>
          <size>0.0010236000000000002 0.0010236000000000002 0.0010236000000000002</size>
        </voxelSize>
        <attributes>
          <displaysettings>0</displaysettings>
        </attributes>
      </ViewSetup>
    </ViewSetups>
    <Timepoints type="range">
      <first>0</first>
      <last>0</last>
    </Timepoints>
  </SequenceDescription>
  <ViewRegistrations>
    <ViewRegistration setup="0" timepoint="0">
      <ViewTransform type="affine">
        <affine>1.0 0.0 0.0 681.632 0.0 1.0 0.0 -270.306 0.0 0.0 1.0 0.0</affine>
        <Name>Translation</Name>
      </ViewTransform>
      <ViewTransform type="affine">
        <affine>0.0010249955593170127 0.00018490055311535682 0.0 0.0 0.00019222474245575595 -0.000998968359065856 0.0 0.0 0.0 0.0 1.0 0.0</affine>
        <Name>MapScaleMat</Name>
      </ViewTransform>
    </ViewRegistration>
    <ViewRegistration setup="0" timepoint="0">
      <ViewTransform type="affine">
        <affine>1.0 0.0 0.0 681.632 0.0 1.0 0.0 -270.306 0.0 0.0 1.0 0.0</affine>
        <Name>Translation</Name>
      </ViewTransform>
      <ViewTransform type="affine">
        <affine>0.0010249955593170127 0.00018490055311535682 0.0 0.0 0.00019222474245575595 -0.000998968359065856 0.0 0.0 0.0 0.0 1.0 0.0</affine>
        <Name>MapScaleMat</Name>
      </ViewTransform>
    </ViewRegistration>
  </ViewRegistrations>
</SpimData>
```

**Comment by NicoKiaru** [comment] 2020-04-22 16:13
The min and max attributes in `<Displaysettings>` are compulsory at the moment. A valid attribute should be:
```
        <Displaysettings>
          <id>0</id>
          <isset>true</isset>
          <color>0 255 255 255</color>
          <min>0.0</min>
          <max>35.955</max>
        </Displaysettings>
```

How did you save this ? Directly in the playground ? Because here these arguments are lacking:
```
<Displaysettings>
          <id>0</id>
          <color>255 255 255 255</color>
          <Projection_Mode>Average</Projection_Mode>
</Displaysettings>
```
You'll need the isset flag also.

In the future I'll probably use json inside these xml tags , this will be wayy easier, also in python.

**Comment by martinschorb** [comment] 2020-04-22 16:16
@constantinpape : how complicated is it to check for these tags upon conversion?
Obviously, I can take care of providing this on my side, but I think the ```displaysettings``` is something pretty essential, so maybe it might be worth parsing it specifically and check if everything is there.

What do you think?

**Comment by martinschorb** [comment] 2020-04-22 16:23
@NicoKiaru: I was ommiting min and max, because this is somewhat redundant if inBDV you select the AutoContrast option. 
One problem with setting it beforehand is that in my conversion I often just want to modify single parts of the metadata and don't even look at the data. For example when converting a large volume, I don't load the full volume into memory, so I have no access to the grey values. Min and Max are very inefficient to retrieve in this case. (https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.memmap.html#numpy.memmap)

In my specific case of TEM data, this is fine because I have Min and Max available in the metadata. There will be other large volumes where this could not be the case.

**Comment by constantinpape** [comment] 2020-04-22 16:36
> @constantinpape : how complicated is it to check for these tags upon conversion?
> Obviously, I can take care of providing this on my side, but I think the `displaysettings` is something pretty essential, so maybe it might be worth parsing it specifically and check if everything is there.

Ok, I can add some additional checks if the attribute name is `displaysettings`.
I think this makes sense and it's very easy to implement.

**Comment by NicoKiaru** [comment] 2020-04-22 17:10
> In my specific case of TEM data, this is fine because I have Min and Max available in the metadata. There will be other large volumes where this could not be the case.

But here, min and max are just for the display, and the data doesn't care about this, if you do not set them, by default (I mean before the existence of `Displaysettings`) the min will be 0 and max 65535, and it just doesn't care about the data (and it's usually not good). Of course you can rely on autocontrast, but that should not prevent you from setting defaults which make sense in most cases. Autocontrast will just override this. 

Isn't copying the settings chosen by the user an option ?

**Comment by NicoKiaru** [comment] 2020-04-22 17:12
@constantinpape 

Are you familiar with json ? Because I think it would be a good idea to serialize the `Displaysettings` inside the xml tag. It's super easy, extensible, standard and is also easy to communicate between python and java.

**Comment by constantinpape** [comment] 2020-04-22 17:16
> Are you familiar with json ? Because I think it would be a good idea to serialize the `Displaysettings` inside the xml tag. It's super easy, extensible, standard and is also easy to communicate between python and java.

Sure, that's not a problem from my side, I can just use the `json.dumps` function in python to make sure we have valid json strings.

**Comment by martinschorb** [comment] 2020-04-24 15:20
Cool,
got the ```displaysettings``` to work in my converter!

Now, I have another request for it:

I need something like "IgnoreAutoContrast". This should force BDV to use the ```min``` and ```max``` Values from the XML to display the source, even if other sources require the autocontrast.

This is extremely crucial when loading tiles from a montage as individual sources. Obviously, you want the contrast scaling for the entire montage to be the same. As it is now, AutoContrast will modify how each individual tile is displayed.

**Comment by NicoKiaru** [comment] 2020-04-24 15:25
> I need something like "IgnoreAutoContrast". This should force BDV to use the `min` and `max` Values from the XML to display the source, even if other sources require the autocontrast.

This is how it behaves if you do not check the autocontrast checkbox when displaying a source normally. Maybe I'm missing something.

And if you want to scale in B&C identically for all sources, you can select all the sources, right-click and select `Adjust Brightness Contrast` (I don't remember exactly the name). Then identical BC settings will be applied to all the sources you've selected. As it's an interactive Command, you can let it open. One missing thing is that there's no way to know which sources were selected when the window is open.

**Comment by martinschorb** [comment] 2020-04-24 15:33
Hi:
let me explain it a bit more detailed:

- I have different datasets, some are created by my converter, some come from somewhere else, without providing any ```displaysettings```.

- Now, what the user does would be to check the ProjectionModes for these other sources

- Since all my datasets behave well (thanks to ```displaysettings```), this is not needed for them

- Now, for laziness, all sources will be selected and "Show"n. Because the sources without ```displaysettings``` need the AutoContrast, this is used by default.

- This leads to all sources being shown with BDVs source-specific contrast (problem for mosaics).

- So I need either a way to disable BDV AutoContrast in the ```displaysettings```, or alternatively "Show Sources" with "AutoContrast" should not act on sources that have ```displaysettings``` and hence proper contrast information.

**Comment by NicoKiaru** [comment] 2020-04-27 14:23
Hmm I see, but I don't think it's a good idea to disable autocontrast if there's a displaysettings present because there's no reason the displaysettings is the one you want  in general (it's not the case for me). Also of you resave the xml dataset, now there will be a displaysettings tag, and maybe the user will find this inconsistent and not know when autocontrast is supposed to work or not (I mean the displaysettings tag is quite hidden for the end user).

You have 2 SpimData I assume, so one way for now is to show all the sources from both spimdata but do not check autocontrast. Then select in the tree the spimdata where you want to adjust the contrast and : either select Brightness Contrast and adjust the B and C for those sources or redo Show Sources and select autocontrast.

THis customized behaviour  can be part of a wizard or otherwise... do you have another idea ?

**Comment by NicoKiaru** [comment] 2022-06-19 08:26
Is this issue still useful @constantinpape ? If yes, please reopen

**Closed as completed by NicoKiaru** 2022-06-19 08:26 UTC
Labels: enhancement
