### ISSUE TITLE
Export source as h5/xml

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#99] opened 2020-03-12 16:00 UTC
Hi,

when I try to export a dataset using right click "Export..."

I get 
```
[ERROR] Module threw error
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: bdv/export/WriteSequenceToHdf5$LoopbackHeuristic
	at sc.fiji.bdvpg.sourceandconverter.exporter.XmlHDF5SpimdataExporter.run(XmlHDF5SpimdataExporter.java:218)
	at sc.fiji.bdvpg.scijava.command.source.XmlHDF5ExporterCommand.run(XmlHDF5ExporterCommand.java:37)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: bdv/export/WriteSequenceToHdf5$LoopbackHeuristic
	... 11 more
Caused by: java.lang.ClassNotFoundException: bdv.export.WriteSequenceToHdf5$LoopbackHeuristic
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

is this because the source is 2D?

**Comment by NicoKiaru** [comment] 2020-03-12 16:08
Hum no unfortunately it's some API change that was not taken into account... Thanks for reporting

**Comment by NicoKiaru** [comment] 2020-03-24 20:19
Should be solved with the last update

**Comment by martinschorb** [comment] 2020-03-25 16:47
I still get an error:

```
SourceAndConverterBdvDisplayService:Create locations display of sourceandconverter of 1
[ERROR] Module threw error
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: bdv/export/WriteSequenceToHdf5$LoopbackHeuristic
	at sc.fiji.bdvpg.sourceandconverter.exporter.XmlHDF5SpimdataExporter.run(XmlHDF5SpimdataExporter.java:218)
	at sc.fiji.bdvpg.scijava.command.source.XmlHDF5ExporterCommand.run(XmlHDF5ExporterCommand.java:37)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: bdv/export/WriteSequenceToHdf5$LoopbackHeuristic
	... 11 more
Caused by: java.lang.ClassNotFoundException: bdv.export.WriteSequenceToHdf5$LoopbackHeuristic
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

**Comment by NicoKiaru** [comment] 2020-03-25 18:11
ok, what are the update sites installed ? can you try with a fresh fiji ?

thanks for reporting

**Comment by martinschorb** [comment] 2020-03-25 18:22
just BigStitcher, nothing else...

**Comment by NicoKiaru** [comment] 2020-03-27 09:37
I don't know if it's the same error but there was an update with BIgStitcher and now it's not working anymore with me as well

**Comment by martinschorb** [comment] 2020-03-27 09:40
I know that Stefan changed something in the exporter here:

https://github.com/PreibischLab/BigStitcher/issues/68

**Comment by NicoKiaru** [comment] 2020-03-27 09:45
Yes, actually I'm not using the exporter of BigStitcher but I have more or less the same function - and I corrected this 2D behaviour before because I had big 2D slide-scanner data to export. However here the problem is an API change of imglib2. I'm relying on the currently imglib2 version of FIJI - but bigstitcher has updated it to a newer version. We need to do this as well in order to make possible to have both this and the BigStitcher update sites enabled in the same FIJI. I'm on it.

**Comment by NicoKiaru** [comment] 2020-03-27 11:14
Ok, so I will do a second update site with an 'alpha' version which will contain all the newer versions of imglib2 and so on because I fear to break this update site more. I'll let you know when it's done

**Comment by NicoKiaru** [comment] 2020-03-27 11:16
For now I'd suggest you keep 2 FIJIs, because of this incompatibility between BigStitcher and the playground

**Comment by NicoKiaru** [comment] 2020-03-27 16:00
Ok, done. FInally I pushed on the same update site. @martinschorb It should work with or without BigStitcher update site. FYI it's a major change because it's now using the new API for bdv, and the new user interface:
You will find that most of the previous shortcuts are disabled ('S') but most commands in the playground still work (please report if not). The new UI is accessible if you look for an arrow on the right part of the window of a bdv.

@tischi the new bdv-ui and bdv-core is now in the branch `alphaversion` the changes are pretty minor in terms of code, but there are a lot of deprecated call now and probably a few broken stuff. Also it requires to build a specific dependency for bdvvistools. We should skype when you have some time

**Comment by NicoKiaru** [comment] 2020-03-31 10:24
Closing now that it's on the update site. Please reopen in case of trouble

**Closed as completed by NicoKiaru** 2020-03-31 10:24 UTC
